# -*- coding: utf-8 -*-
source 'https://rubygems.org'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry'
  gem 'pry-byebug'
end

gem "google-api-client"
gem "google-cloud-datastore"
gem "kura"
gem "rmagick"

